### ISSUE TITLE
How is the `dataset` described in Readme define?

### ISSUE THREAD

**Issue by LaureatePoet** [kajyuuen/Dawid-skene#2]
```python
from dawid_skene_model import list2array
from dawid_skene_model import DawidSkeneModel

class_num = 4
dataset = [
        [[0, 0, 0], [0], [0], [0], [0]],
        [[2, 2, 2], [3], [2], [2], [3]],
        [[0, 0, 1], [1], [0], [1], [1]]
]
dataset_tensor = list2array(class_num, dataset_list)
model = DawidSkeneModel(class_num, max_iter=45, tolerance=10e-100)
marginal_predict, error_rates, worker_reliability, predict_label = model.run(dataset_tensor)
```

The number of categories is 4, how should the dataset be understood? 
e.g. the`dataset[0]`: what is `[0, 0, 0]`, what is `[0], [0], [0], [0]`

**Comment by kajyuuen** [comment]
I'm not sure because the code is quite old, but I think that dataset[0][0] is the result of one annotator annotating three times, and dataset[0][1:5] is the result of each annotator annotating once.

**Comment by kajyuuen** [comment]
This is probably correct since [this test code](https://github.com/kajyuuen/Dawid-skene/blob/6cdf3a4d429b8839a57eaf67e6412eaf24d56edb/test_dawid_skene_model.py#L9-L56) matches [Table 1 of this paper](https://www.semanticscholar.org/paper/Maximum-Likelihood-Estimation-of-Observer-Using-the-Dawid-Skene/c80c7ab615b2fad5148a7848dbdd26a2dc50dd3d).

**Comment by LaureatePoet** [comment]
Okay, thank you for your reply. I'll give it a try and let you know if there's any good news.

**Comment by kajyuuen** [comment]
Thank you. Please send a PR if there are any improvements.
